<?php
$title = 'Add new album';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('album', array('action' => 'add')));
$form->prepare();
?>
<?php if ($form->getMessages()): ?>
    <div class="alert alert-error">
        <button class="close" data-dismiss="alert" type="button">×</button>
        <strong>Invalid input!</strong>
        The form fields are not filled out correctly.
    </div>
<?php endif; ?>
<?php 
echo $this->form()->openTag($form);
echo $this->formTwb($form);
echo $this->form()->closeTag();
?>